version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
      - ../../USA_segmentation:/app/data
    environment:
      - DATA_ROOT=/app/data
